name: Publish

on:
  pull_request:
    branches: [main]
    paths:
      - "blogs/**"
      - "!README.md"
  push:
    branches: [main]
    paths:
      - "blogs/**"
      - "!README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - name: Get Repo
        uses: actions/checkout@v3

      - name: Get Changed Files
        id: files
        uses: Ana06/get-changed-files@v2.2.0
        with:
          format: "csv"
          filter: "*.md"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pip -U
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Publish Article
        run: |
          files="${{ steps.files.outputs.added_modified }}"
          mapfile -d ',' -t added_modified_files < <(printf '%s,' '${{ steps.files.outputs.added_modified }}')
          if [[ ${#files} -gt 0 ]]; then
            echo "Publishing articles to DEV.to 🎉"
            for added_modified_file in "${added_modified_files[@]}"; do
              echo "Do something with this ${added_modified_file}."
              poetry run script/publish.py ${added_modified_file}
            done
          else
            echo "No posts to publish"
          fi

      - name: Auto Commit Message
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[auto] Article is published 🚀"
